- name: Docker Installation and User Configuration
  hosts: all
  become: true
  gather_facts: false
  vars:
    user: mahe

  tasks:
    - name: Install Docker Dependencies
      apt:
        update_cache: yes
        name:
          - lsb-release
          - ca-certificates
          - curl
          - gnupg

    - name: Install GPG Key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Install Docker Engine
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: latest
        update_cache: yes

    - name: Install Python Dependencies
      apt:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: latest
        executable: pip3

    - name: Add user to the docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes
        state: present
      become: true

    - name: Install NodeSource repository GPG key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Install NodeSource repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x focal main
        state: present
        filename: nodesource.list

    - name: Install Node.js version 14
      apt:
        name: nodejs
        state: present
        update_cache: yes

- name: Ansible Copy Example Local to Remote
  hosts: appserver
  become: true
  gather_facts: false
  tasks:
    - name: Copy file docker-compose
      copy:
        src: ~/ansible/storehouse/docker-compose.yml
        dest: /home/mahe/docker-compose.yml
        owner: mahe
        group: mahe

    - name: Clone Git repository
      git:
        repo: https://github.com/dumbwaysdev/wayshub-frontend
        dest: /home/mahe/wayshub-frontend
        clone: yes
        force: yes

    - name: Copy file Dockerfile
      copy:
        src: ~/ansible/storehouse/Dockerfile
        dest: /home/mahe/wayshub-frontend
        owner: mahe
        group: mahe

    - name: Run docker-compose
      command: docker compose up -d
      args:
        chdir: /home/mahe/wayshub-frontend
