global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['34.67.55.176:9090']  # ip monitoring
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['34.67.55.176:9100','34.67.55.176:9100']  # ip appserver,gateway
