- hosts: all  #dari inventory
  become: true # menjadi sudo
  tasks:
    - name: Membuat user 
      user:
        name: mahe
        groups: sudo
        state: present  #state itu adalah perintah untuk mengecek objek/package/  present: memastikan/harus ada // absent: menghapus // latest : versi baru
        shell: /bin/bash #user menggunakan bash
        system: no #pengguna akan dianggap sebagai pengguna sistem
        createhome: yes
        home: /home/mahe

    - name: Copy SSH public key ke remote host 
      authorized_key:
        user: mahe
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  
        state: present

    - name: Configure PasswordAuthentication for ssh
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'  
        state: present
      notify:
        - Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
 
